# Generated by Django 3.2.12 on 2022-04-15 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220414_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 15, 1, 12, 780032, tzinfo=utc), null=True),
        ),
    ]
